server.port: 8084

spring:
  application:
    name: notification-service

  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: sa-east-1
      credentials:
        access-key: test
        secret-key: test


notification-service:
  sqs:
    order:
      queue-name: NOTIFICATION_SERVICE_ORDER_QUEUE


