version: '3.8'

services:
  localstack:
    image: localstack/localstack:4
    container_name: saga-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs
      - DEFAULT_REGION=sa-east-1
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - localstack_data:/var/lib/localstack
      - ./localstack-init.sh:/etc/localstack/init/ready.d/localstack-init.sh:ro
    networks:
      - saga-pattern-choreography
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 5s
      timeout: 3s
      retries: 10

  postgres:
    image: postgres:16-alpine
    container_name: saga-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - saga-pattern-choreography
    volumes:
      - ./create-postgres-dbs.sh:/docker-entrypoint-initdb.d/create-postgres-dbs.sh:ro
      - postgres_data:/var/lib/postgresql/data

networks:
  saga-pattern-choreography:
    driver: bridge

volumes:
  localstack_data:
  postgres_data:
