spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: sa-east-1
      credentials:
        access-key: test
        secret-key: test

server:
  port: 8080

order-service:
  sqs:
    order-status:
      queue-name: ORDER_SERVICE_STATUS_QUEUE
  sns:
    order-action:
      topic-arn: arn:aws:sns:sa-east-1:000000000000:ORDER_ACTION
